version: "2"
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    volumes:
      - ./backend/src/queries/create.sql:/docker-entrypoint-initdb.d/create.sql
  backend:
    build:
      context: ${PWD}/backend
      dockerfile: ${PWD}/backend/dev.Dockerfile
    environment:
      BACKEND_URI: 3500
    ports:
      - "3500:3500"
    command: "yarn start:dev"