swagger: '2.0'
info:
  description: "House Sensing Project"
  version: "1.0.0"
  title: "House Sensing Project"
  termsOfService: ""
host: "localhost:3500"
basePath: "/"
paths:
  "/sensors":
    get:
      description: Retrieves all pir sensor data
      operationId: retrievePIR
      tags:
        - Sensors
      responses:
        200:
          description: All PIR Sensor retrieved successfully
          schema:
            $ref: "#/definitions/sensorPIRBase"
        400:
          description: Unauthenticated User
          schema:
            $ref: "#/definitions/unauthenticatedResponse"
        default:
          description: Internal Error
          schema:
            $ref: '#/definitions/defaultResponse'
    post:
      description: Create new PIR data
      operationId: createPIR
      tags:
        - Sensors
      parameters:
        - in: query
          required: true
          name: reading
          type: integer
      responses:
        200:
          description: Created new PIR data
          schema:
            $ref: '#/definitions/createPIRBase'
        400:
          description: Unauthenticated User
          schema:
            $ref: "#/definitions/unauthenticatedResponse"
        default:
          description: Internal Error
          schema:
            $ref: '#/definitions/defaultResponse'
  '/sensors/{id}':
    get:
      description: Retrieves Sensor using Id
      operationId: retrieveSensorById
      tags:
        - Sensors
      parameters:
        - in: path
          required: true
          name: id
          type: integer
      responses:
        200:
          description: Succesfully retrieved sensor
          schema:
            type: array
            items:
              $ref: "#/definitions/sensorPIRBase"
        default:
          description: Internal Error
          schema:
            $ref: "#/definitions/defaultResponse"
  '/sensors/{type}/type':
    get:
      description: Retrieves All sensors according to the given Sensor Type
      operationId: retrieveSensorByType
      tags:
        - Sensors
      parameters:
        - in: path
          required: true
          type: string
          name: type
      responses:
        200:
          description: Successfully retrieves type
          schema:
            type: array
            items:
              $ref: "#/definitions/sensorPIRBase"
        default:
          description: Internal Error
          schema:
            $ref: "#/definitions/defaultResponse"
definitions:
  sensorPIRBase:
    type: object
    properties:
      sensor_type:
        type: string
      reading:
        type: number
  createPIRBase:
    type: object
  unauthenticatedResponse:
    type: object
  defaultResponse:
    type: object