version: "3.5"
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
    volumes:
      - ./../backend/src/queries/create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - fjcamillo_network
      - shella_network
  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/vhost.d"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #   - ./data/certbot/conf:/etc/letsencrypt
    #   - ./data/certbot/www:/var/www/certbot
    networks:
      - fjcamillo_network
      - shella_network
  redis:
    image: redis:5.0.4-alpine
    # volumes:
    #   - /app/redis/:/data
    networks:
      - fjcamillo_network
      - shella_network
  # certbot:
  #   image: certbot/certbot
  #   networks:
  #     - fjcamillo_network
  #     - shella_network
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot

networks:
  fjcamillo_network:
    name: fjcamillo_networks
  shella_network:
    name: shella_networks