version: "3"
services:
  backend:
    build:
      context: ${PWD}/../backend
      dockerfile: ${PWD}/../backend/dev.Dockerfile
    environment:
      BACKEND_PORT: 3500
      BACKEND_URI: dev-api.fjcamillo.com
      DATABASE_USER: test
      DATABASE_PASSWORD: test
      DATABASE_HOST: postgres
      DATABASE_NAME: house
      DATABASE_PORT: 5432
      VIRTUAL_HOST: dev-api.fjcamillo.com
    ports:
      - "3500:3500"
    volumes:
      - ${PWD}/../backend:/app
    command: "yarn start:dev"
    # networks:
    
networks:
  default:
    external:
      name: fjcamillo_networks
