version: "3"
services:
  backend:
    build:
      context: ${PWD}/../backend
      dockerfile: ${PWD}/../backend/dev.Dockerfile
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_URI: ${BACKEND_URI}
      VIRTUAL_HOST: dev-api.fjcamillo.com
    ports:
      - "3500:3500"
    volumes:
      - ${PWD}/../backend:/app
    command: "yarn start:dev"
    # networks:
    
networks:
  default:
    external:
      name: fjcamillo_networks
