version: "3"
services:
  backend:
    build:
      context: ${PWD}/../backend
      dockerfile: ${PWD}/../backend/dev.Dockerfile
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_URI: ${BACKEND_URI}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      VIRTUAL_HOST: ${BACKEND_URI}
    ports:
      - "3500:3500"
    volumes:
      - ${PWD}/../backend:/app
    command: "yarn start:dev"
    # networks:
    
networks:
  default:
    external:
      name: fjcamillo_networks
